name: build-windows

on:
  workflow_dispatch:

jobs:
  windows-cpp-build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - cuda: '12.8.1'
            rapids-cmake-branch: 'release/26.02'
          - cuda: '13.1.0'
            rapids-cmake-branch: 'main'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: Jimver/cuda-toolkit@v0.2.30
        with:
          cuda: ${{ matrix.cuda }}
          method: 'network'
      - name: Configure
        run: cmake -S cpp -B build -DBUILD_TESTS=ON -Drapids-cmake-branch=${{ matrix.rapids-cmake-branch }}
      - name: Build
        run: cmake --build build --config Release --parallel
